bool isWifiOn();
u8 getWifiLevel();
char* getIPAddress();
void initSocketing();
void termSocketing();
Socket* createServerSocket(int port);
Packet* socketRecv(Socket* my_socket, u32 size);
void socketSend(Socket* my_socket, char* text);
Socket* serverAccept(Socket* my_socket);
void socketClose(Socket* my_socket);